name: Executar Testes Flutter

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted # Define que rodará no seu runner local
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Testes
        run: flutter test